// Generated by CoffeeScript 1.6.2
(function() {
  define(["config/underscore/templatesettings", "config/marionette/templatecache", "config/marionette/region/dialog"], function() {});

}).call(this);
