// Generated by CoffeeScript 1.6.2
(function() {
  define(["config/marionette/templatecache", "config/marionette/region/dialog", "config/underscore/templatesettings"], function() {});

}).call(this);
