// Generated by CoffeeScript 1.6.2
(function() {
  define(["underscore", "backbone", "marionette", "msgbus", "bsModal"], function(_, Backbone, Marionette, msgBus) {
    var app,
      _this = this;

    app = new Marionette.Application();
    app.defaultSearchTerm = "West Highland Terrier";
    app.addRegions({
      content: "#content",
      menu: "#menu",
      modal: Marionette.Region.Dialog.extend({
        el: "#modal"
      })
    });
    app.on("initialize:after", function() {
      if (!Backbone.history.started) {
        return Backbone.history.start();
      }
    });
    app.addInitializer(function() {
      return msgBus.commands.execute("books:route");
    });
    msgBus.events.on("app:show:modal", function(view) {
      return app.modal.show(view);
    });
    msgBus.events.on("app:show", function(view) {
      return app.content.show(view);
    });
    return app;
  });

}).call(this);
