// Generated by CoffeeScript 1.6.3
(function() {
  require.config({
    baseURL: 'assetsAMD/js',
    paths: {
      jquery: "../../bower_components/jquery/jquery",
      underscore: "../../bower_components/underscore-amd/underscore",
      backbone: "../../bower_components/backbone-amd/backbone",
      "backbone.wreqr": "../../bower_components/backbone.wreqr/lib/amd/backbone.wreqr",
      "backbone.babysitter": "../../bower_components/backbone.babysitter/lib/amd/backbone.babysitter",
      marionette: "../../bower_components/marionette/lib/core/amd/backbone.marionette",
      bsModal: "../../bower_components/bootstrap/js/modal",
      text: "../../bower_components/requirejs-text/text"
    },
    shim: {
      bsModal: ["jquery"]
    }
  }, require(["config/_base", "app", "apps/book/app", "apps/other/app"], function(_config, App) {
    return App.start();
  }));

}).call(this);
