// Generated by CoffeeScript 1.6.2
(function() {
  define(function(require) {
    return {
      book: require('text!templates/book.htm'),
      bookdetail: require('text!templates/bookdetail.htm'),
      booklist: require('text!templates/booklist.htm'),
      librarylayout: require('text!templates/librarylayout.htm'),
      secondapp: require('text!templates/secondapp.htm')
    };
  });

}).call(this);
