// Generated by CoffeeScript 1.6.2
(function() {
  define(['underscore'], function(_) {
    return (function() {
      return _.templateSettings = {
        evaluate: /\{\[([\s\S]+?)\]\}/g,
        interpolate: /\{\{(.+?)\}\}/g
      };
    })();
  });

}).call(this);
