// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["marionette"], function(Marionette) {
    var router, _ref;

    return router = (function(_super) {
      __extends(router, _super);

      function router() {
        _ref = router.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      router.prototype.appRoutes = {
        "": "defaultSearch",
        "search/:searchTerm": "search"
      };

      return router;

    })(Marionette.AppRouter);
  });

}).call(this);
