// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["backbone", "views/secondappview", "msgbus"], function(Backbone, AppView, msgBus) {
    var Router, _ref;

    return {
      Router: Router = (function(_super) {
        __extends(Router, _super);

        function Router() {
          _ref = Router.__super__.constructor.apply(this, arguments);
          return _ref;
        }

        Router.prototype.appRoutes = {
          "secondapp": "start"
        };

        return Router;

      })(Backbone.Marionette.AppRouter),
      start: function() {
        var view;

        view = new AppView();
        msgBus.events.trigger("app:show", view);
        return Backbone.history.navigate('secondapp');
      }
    };
  });

}).call(this);
