// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["underscore", "marionette", "templates"], function(_, Marionette, templates) {
    "use strict";
    var view, _ref;

    return view = (function(_super) {
      __extends(view, _super);

      function view() {
        _ref = view.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      view.prototype.template = _.template(templates.bookdetail);

      view.prototype.className = "modal bookDetail";

      return view;

    })(Marionette.ItemView);
  });

}).call(this);
