// Generated by CoffeeScript 1.6.2
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  define(["underscore", "marionette", "templates", "views/bookdetail", "msgbus"], function(_, Marionette, templates, BookDetailView, msgbus) {
    var View, _ref;

    return View = (function(_super) {
      __extends(View, _super);

      function View() {
        _ref = View.__super__.constructor.apply(this, arguments);
        return _ref;
      }

      View.prototype.template = _.template(templates.book);

      View.prototype.events = {
        click: "showBookDetail"
      };

      View.prototype.showBookDetail = function() {
        var detailView;

        detailView = this.getDetailView;
        return msgbus.events.trigger("app.show.modal", detailView);
      };

      View.prototype.getDetailView = function() {
        return new BookDetailView({
          model: this.model
        });
      };

      return View;

    })(Marionette.ItemView);
  });

}).call(this);
